version: '3.8'

services:
  app_db:
    container_name: app_db
    image: postgres:15.1-alpine
    volumes:
      - /psql:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - app_network
    expose:
      - 5432
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}}'"]
      interval: 10s
      timeout: 5s
      retries: 10

  app_redis:
    container_name: app_redis
    image: redis:latest
    env_file:
      - .env
    networks:
      - app_network
    expose:
      - 6379
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  app_rabbitmq:
    container_name: app_rabbitmq
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    env_file:
      - .env
    networks:
      - app_network
    expose:
      - 5672
      - 15672
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test:  ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  psql:

networks:
  app_network:
    name: app_network
