version: '3.8'

services:

  app_redis:
    container_name: app_redis
    image: redis:latest
    env_file:
      - .env
    networks:
      - app_network
    expose:
      - 6379
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  app_celery:
    container_name: app_celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A elink worker
    restart: always
    env_file:
      - .env
    depends_on:
      - redis_db

  app_celery_beat:
    container_name: app_celery_beat
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A elink beat
    restart: always
    env_file:
      - .env
    depends_on:
      - redis_db

networks:
  app_network:
    name: app_network
