# Generated by Django 4.1.7 on 2023-03-23 20:32

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries_app', '0005_alter_city_latitude_alter_city_longitude'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='language',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
