# Generated by Django 4.1.7 on 2023-03-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries_app', '0006_alter_language_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='language',
            managers=[
            ],
        ),
    ]
